/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Administrator
 */
public class PomBensinGUI extends javax.swing.JFrame {

    /**
     * Creates new form PomBensinGUI
     */
    public PomBensinGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonPremium21552011440 = new javax.swing.JButton();
        ButtonPertamax21552011440 = new javax.swing.JButton();
        LabelJudul21552011440 = new javax.swing.JLabel();
        jNominal21552011440 = new javax.swing.JTextField();
        LabelNominal21552011440 = new javax.swing.JLabel();
        LabelPilih21552011440 = new javax.swing.JLabel();
        jLiter21552011440 = new javax.swing.JTextField();
        LabelLiter21552011440 = new javax.swing.JLabel();
        ButtonPertalite21552011440 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonPremium21552011440.setText("Premium");
        ButtonPremium21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPremium21552011440ActionPerformed(evt);
            }
        });

        ButtonPertamax21552011440.setText("Pertamax");
        ButtonPertamax21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPertamax21552011440ActionPerformed(evt);
            }
        });

        LabelJudul21552011440.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        LabelJudul21552011440.setText("Pom Shell");

        LabelNominal21552011440.setText("Nominal");

        LabelPilih21552011440.setText("Pilih Bahan Bakar DiBawah");

        jLiter21552011440.setEditable(false);

        LabelLiter21552011440.setText("Liter");

        ButtonPertalite21552011440.setText("Pertalite");
        ButtonPertalite21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPertalite21552011440ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jNominal21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LabelNominal21552011440))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonPertalite21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLiter21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelLiter21552011440))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelPilih21552011440))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(LabelJudul21552011440))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ButtonPremium21552011440, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonPertamax21552011440, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabelJudul21552011440)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNominal21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNominal21552011440))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLiter21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelLiter21552011440))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelPilih21552011440)
                .addGap(18, 18, 18)
                .addComponent(ButtonPertalite21552011440)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonPremium21552011440)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonPertamax21552011440)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPertalite21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPertalite21552011440ActionPerformed
     double nominal = Double.parseDouble(jNominal21552011440.getText());
     double Pertalite = nominal/7650;
     jLiter21552011440.setText(String.format("%.2f", Pertalite));
    }//GEN-LAST:event_ButtonPertalite21552011440ActionPerformed

    private void ButtonPremium21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPremium21552011440ActionPerformed
     double nominal = Double.parseDouble(jNominal21552011440.getText());
     double Premium = nominal/7100;
     jLiter21552011440.setText(String.format("%.2f", Premium));
    }//GEN-LAST:event_ButtonPremium21552011440ActionPerformed

    private void ButtonPertamax21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPertamax21552011440ActionPerformed
     double nominal = Double.parseDouble(jNominal21552011440.getText());
     double Pertamax = nominal/9000;
     jLiter21552011440.setText(String.format("%.2f", Pertamax));
    }//GEN-LAST:event_ButtonPertamax21552011440ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PomBensinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PomBensinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PomBensinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PomBensinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PomBensinGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonPertalite21552011440;
    private javax.swing.JButton ButtonPertamax21552011440;
    private javax.swing.JButton ButtonPremium21552011440;
    private javax.swing.JLabel LabelJudul21552011440;
    private javax.swing.JLabel LabelLiter21552011440;
    private javax.swing.JLabel LabelNominal21552011440;
    private javax.swing.JLabel LabelPilih21552011440;
    private javax.swing.JTextField jLiter21552011440;
    private javax.swing.JTextField jNominal21552011440;
    // End of variables declaration//GEN-END:variables
}
